# https://github.com/travis-ci/travis-ci/wiki/.travis.yml-options

dist: xenial
language: python
install: "ci/install.sh"
#script: "src/manage.py test project sa_api_v2 remote_client_user --with-coverage --cover-package=sa_api_v2 --cover-package=remote_client_user"
script: "src/manage.py test project sa_api_v2 --with-coverage --cover-package=sa_api_v2"
python:
  - "2.7"
  - "3.6"
notifications:
  irc:
    channels:
      - "irc.freenode.org#shareabouts"
    on_success: change
    on_failure: always
  email:
    recipients:
     - dev@openplans.org
    on_success: change
    on_failure: always

# branches:
#   only:
#     - master
